routes/web.php
<?php

use App\Http\Controllers\Controller;
use App\Http\Controllers\TicketCommentController;
use App\Http\Controllers\TicketController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => 'auth:web'], function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('/tickets', [TicketController::class, 'store'])->name('tickets.store');
    Route::get('/tickets/{ticket}', [TicketController::class, 'show'])->name('tickets.show');
});

Route::group(['middlware' => ['admin']], function(){
    Route::put('/tickets/{ticket}/change-status', [TicketController::class, 'changeStatus'])->name('tickets.change_status');
    Route::get('/tickets', [TicketController::class, 'index'])->name('tickets.index');
    Route::post('/tickets/{ticket}/comments', [TicketCommentController::class, 'store'])->name('comments.store');
});

Route::get('/files/private/{path}', [Controller::class, 'privateFileDownload'])
    ->where('path', '.*');

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Storage;

class Ticket extends Model
{
    use HasFactory;
    public $fillable = [
        'title',
        'description',
        'attachment',
        'importance',
        'name',
        'email',
        'phone_number',
    ];

    public $hidden = [
        'updated_at',
        'user_id',
    ];

    public function statusHistory(){
        return $this->hasMany(TicketStatusHistory::class);
    }

    public function comments(){
        return $this->hasMany(TicketComment::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function getAttachmentUrlAttribute(){
        // create a temp token to secure the download request
        $token = auth()->user()->createToken('storage_access', [], now()->addMinutes(30))->plainTextToken;
        return Storage::disk('private')->url($this->getAttribute('attachment')."?token=$token");
    }
}

app/Http/Controllers/Api/TicketController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\TicketChangeStatusRequest;
use App\Http\Requests\TicketShowRequest;
use App\Http\Requests\TicketStoreRequest;
use App\Http\Resources\TicketResource;
use App\Mail\TicketClosedMail;
use App\Models\Ticket;
use App\Repository\TicketCommentRepositoryInterface;
use App\Repository\TicketRepositoryInterface;
use App\Repository\TStatusHistoryRepositoryInterface;
use Illuminate\Http\Request;
use Mail;

class TicketController extends Controller
{
    private $ticketRepository;
    private $statusHistoryRepository;
    private $commentRepository;
    public function __construct(TicketRepositoryInterface $ticketRepository,TStatusHistoryRepositoryInterface $statusHistoryRepository, TicketCommentRepositoryInterface $commentRepository) {
        $this->ticketRepository = $ticketRepository;
        $this->statusHistoryRepository = $statusHistoryRepository;
        $this->commentRepository = $commentRepository;
    }

    public function index(Request $request)
    {
        $search = $request->input('search');
        $sort = $request->input('sort', 'created_at');
        $direction = $request->input('direction', -1);
        $tickets = $this->ticketRepository->getPaginatedTickets($search, $sort, $direction);

        return apiResponse(
            TicketResource::collection($tickets),
            null,
            200,
            $tickets
        );
    }

    public function changeStatus(TicketChangeStatusRequest $request, Ticket $ticket){
        $old_status = $ticket->status;
        $this->ticketRepository->changeStatus($ticket, $request->validated()['new_status']);
        $this->ticketRepository->createHistoryRecord($ticket->refresh(), $old_status);

        $ticket->status == 'closed' ? Mail::to($ticket->email)->send(new TicketClosedMail($ticket)) : null;
        
        return apiResponse(
            TicketResource::make($ticket),
            "Status changed successfully!",
            200,
        );
    } 
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Http\Actions\Ticket\TicketClosedMailStrategy;
use App\Http\Actions\Ticket\TicketClosedNotifyAction;
use App\Http\Actions\Ticket\TicketStoreMailAction;
use App\Http\Actions\Ticket\TicketStoreMailStrategy;
use App\Http\Actions\Ticket\TicketStoreNotifyAction;
use App\Http\Requests\TicketChangeStatusRequest;
use App\Http\Requests\TicketShowRequest;
use App\Http\Requests\TicketStoreRequest;
use App\Mail\TicketClosedMail;
use App\Models\Ticket;
use App\Repository\TicketCommentRepositoryInterface;
use App\Repository\TicketRepositoryInterface;
use App\Repository\TStatusHistoryRepositoryInterface;
use Illuminate\Http\Request;
use Mail;

class TicketController extends Controller
{
    private $ticketRepository;
    private $statusHistoryRepository;
    private $commentRepository;
    public function __construct(TicketRepositoryInterface $ticketRepository,TStatusHistoryRepositoryInterface $statusHistoryRepository, TicketCommentRepositoryInterface $commentRepository) {
        $this->ticketRepository = $ticketRepository;
        $this->statusHistoryRepository = $statusHistoryRepository;
        $this->commentRepository = $commentRepository;
    }

    public function index(Request $request)
    {
        $search = $request->input('search');
        $sort = $request->input('sort', 'created_at');
        $direction = $request->input('direction', -1);
        $tickets = $this->ticketRepository->getPaginatedTickets($search, $sort, $direction);

        return view('tickets.index', ['tickets' => $tickets]);
    }

    public function show(TicketShowRequest $request, Ticket $ticket){
        return view('tickets.show', [
            'ticket' => $ticket,
            'status_history' => $this->statusHistoryRepository->getOfTicket($ticket),
            'comments' => $this->commentRepository->getOfTicket($ticket),
        ]);
    }
    public function store(TicketStoreRequest $request)
    {
        $ticket = $this->ticketRepository->createTicket($request->validated());

        $request->session()->flash('success', 'Thanks for submitting your ticket!');
        $request->session()->flash('link', route('tickets.show', ['ticket' => $ticket->id]));
        TicketStoreNotifyAction::make(new TicketStoreMailStrategy($ticket))->perform();
        return redirect($request->input('redirect'));
    }
    
    public function changeStatus(TicketChangeStatusRequest $request, Ticket $ticket){
        $old_status = $ticket->status;
        $this->ticketRepository->changeStatus($ticket, $request->validated()['new_status']);
        $this->ticketRepository->createHistoryRecord($ticket->refresh(), $old_status);

        $ticket->status == 'closed' ? TicketClosedNotifyAction::make(new TicketClosedMailStrategy($ticket))->perform() : null;

        return redirect($request->input('redirect'));
    } 
}

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')
    @vite(['resources/css/tickets/index.css'])

    <div class="container">
        <h1>Ticket List</h1>

        <div class="mb-3">
            <form action="{{ route('tickets.index', request()->query()) }}" method="GET" class="form-inline">
                <input type="text" name="search" class="form-control mr-sm-2" placeholder="Search">
                @foreach (request()->query() as $k => $field)
                    <input hidden type="text" name="{{ $k }}" class="form-control mr-sm-2"
                        value="{{ $field }}">
                @endforeach
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th><a
                            href="{{ route('tickets.index', ['sort' => 'title', 'direction' => request()->sort == 'title' ? (request()->direction *= -1) : 1] + request()->query()) }}">Title</a>
                    </th>
                    <th><a
                            href="{{ route('tickets.index', ['sort' => 'name', 'direction' => request()->sort == 'name' ? (request()->direction *= -1) : 1] + request()->query()) }}">Name</a>
                    </th>
                    <th><a
                            href="{{ route('tickets.index', ['sort' => 'created_at', 'direction' => request()->sort == 'created_at' ? (request()->direction *= -1) : 1] + request()->query()) }}">Date</a>
                    </th>
                    <th><a
                            href="{{ route('tickets.index', ['sort' => 'importance', 'direction' => request()->sort == 'importance' ? (request()->direction *= -1) : 1] + request()->query()) }}">Importance</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach ($tickets as $k => $ticket)
                    <div>
                        <tr class="hover-tr" id="row-{{ $k }}">
                            <td>{{ $ticket->title }}</td>
                            <td>{{ $ticket->name }}</td>
                            <td>{{ $ticket->created_at }}</td>
                            <td class="{{ getImportanceBadgeClass($ticket->importance) }}">{{ $ticket->importance }}</td>
                        </tr>
                    </div>
                @endforeach
            </tbody>
        </table>
        <script>
            @foreach ($tickets as $k => $ticket)
                const row{{ $k }} = document.getElementById(`row-{{ $k }}`);
                row{{ $k }}.addEventListener("click", () => {
                    window.location.href = '{{ route('tickets.show', ['ticket' => $ticket->id]) }}';
                });
            @endforeach
        </script>

        <div class="pagination">
            {{ $tickets->links() }}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
@endsection

resources/views/tickets/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-header">
                        <h5 class="card-title">Ticket Details</h5>
                    </div>
                    <div class="card-body">
                        <p><strong>Title:</strong> {{ $ticket->title }}</p>
                        <p><strong>Description:</strong> {{ $ticket->description }}</p>
                        <p><strong>Attachment:</strong>
                            @if ($ticket->attachment)
                                <a href="{{ $ticket->attachment_url }}" download>Download Attachment</a>
                            @else
                                No attachment
                            @endif
                        </p>
                        <p><strong>Importance :</strong> <span
                                class="badge {{ getImportanceBadgeClass($ticket->importance) }}">{{ Str::upper($ticket->importance) }}</span>
                        </p>
                        <p><strong>Status:</strong> <span
                                class="badge {{ getStatusBadgeClass($ticket->status) }}">{{ getStatusText($ticket->status) }}</span>
                        </p>
                        @if (session('success'))
                            <div class="alert alert-success">
                                Status changes successfully!
                            </div>
                        @endif
                        <form id="change-status-form"
                            action='{{ route('tickets.change_status', ['ticket' => $ticket->id]) }}' method="POST">
                            @csrf
                            <input type="hidden" name="redirect"
                                value="{{ route('tickets.show', ['ticket' => $ticket->id]) }}">
                            <input hidden type="text" name="_method" value="PUT">
                            <select {{!auth()->user()->hasRole('admin') ? 'disabled' : ''}} name="new_status" class="form-select col-md-6" aria-label="Change status"
                                onchange="changeStatus()">
                                <option {{ $ticket->status == 'pending' ? 'selected' : '' }} value="pending">Pending
                                </option>
                                <option {{ $ticket->status == 'in_progress' ? 'selected' : '' }} value="in_progress">In
                                    progress</option>
                                <option {{ $ticket->status == 'closed' ? 'selected' : '' }} value="closed">Closed</option>
                            </select>
                        </form>
                        <br />
                        @foreach ($status_history as $status)
                            <p>
                                Status changed from
                                <span
                                    class="{{ getStatusBadgeClass($status->old_status) }}">{{ getStatusText($status->old_status) }}</span>
                                to
                                <span
                                    class="{{ getStatusBadgeClass($status->new_status) }}">{{ getStatusText($status->new_status) }}</span>
                                on {{ $status->created_at->format('Y-m-d H:i:s') }}
                            </p>
                        @endforeach
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Comments</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            @foreach ($comments->reverse() as $comment)
                                <li class="list-group-item">
                                    <h6>{{ $comment->user->name }} | {{ $comment->created_at }}</h6>
                                    <p>{{ $comment->body }}</p>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                    @if(auth()->user()->hasRole('admin'))
                    <div class="card-footer">
                        <form action="{{ route('comments.store', ['ticket' => $ticket->id]) }}" method="POST">
                            @csrf
                            <input type="hidden" name="redirect"
                                value="{{ route('tickets.show', ['ticket' => $ticket->id]) }}">
                            <div class="form-group">
                                <textarea class="form-control" name="body" rows="3" placeholder="Add a comment"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Add Comment</button>
                        </form>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <script>
        function changeStatus() {
            document.getElementById("change-status-form").submit();
        }
    </script>
@endsection